//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.FoodWS
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.foodapi.miwfit.ws.miw.uniovi.es/")]
    public partial class CaloriesMustBePositiveException
    {
        
        private string faultCodeField;
        
        private string faultStringField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultCode
        {
            get
            {
                return this.faultCodeField;
            }
            set
            {
                this.faultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultString
        {
            get
            {
                return this.faultStringField;
            }
            set
            {
                this.faultStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.foodapi.miwfit.ws.miw.uniovi.es/")]
    public partial class food
    {
        
        private double azucaresField;
        
        private double caloriesField;
        
        private string comidaField;
        
        private string flickrnameField;
        
        private double gramosField;
        
        private double gramosPorRacionField;
        
        private double grasasField;
        
        private string nameField;
        
        private double proteinaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double azucares
        {
            get
            {
                return this.azucaresField;
            }
            set
            {
                this.azucaresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double calories
        {
            get
            {
                return this.caloriesField;
            }
            set
            {
                this.caloriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string comida
        {
            get
            {
                return this.comidaField;
            }
            set
            {
                this.comidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string flickrname
        {
            get
            {
                return this.flickrnameField;
            }
            set
            {
                this.flickrnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double gramos
        {
            get
            {
                return this.gramosField;
            }
            set
            {
                this.gramosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double gramosPorRacion
        {
            get
            {
                return this.gramosPorRacionField;
            }
            set
            {
                this.gramosPorRacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double grasas
        {
            get
            {
                return this.grasasField;
            }
            set
            {
                this.grasasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double proteina
        {
            get
            {
                return this.proteinaField;
            }
            set
            {
                this.proteinaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.foodapi.miwfit.ws.miw.uniovi.es/", ConfigurationName="WSClient.FoodWS.FoodProvider")]
    public interface FoodProvider
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.foodapi.miwfit.ws.miw.uniovi.es/FoodProvider/getFoodRequest", ReplyAction="http://webservices.foodapi.miwfit.ws.miw.uniovi.es/FoodProvider/getFoodResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSClient.FoodWS.CaloriesMustBePositiveException), Action="http://webservices.foodapi.miwfit.ws.miw.uniovi.es/FoodProvider/getFood/Fault/Cal" +
            "oriesMustBePositiveException", Name="CaloriesMustBePositiveException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSClient.FoodWS.getFoodResponse> getFoodAsync(WSClient.FoodWS.getFoodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFood", WrapperNamespace="http://webservices.foodapi.miwfit.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class getFoodRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.foodapi.miwfit.ws.miw.uniovi.es/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg0;
        
        public getFoodRequest()
        {
        }
        
        public getFoodRequest(double arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFoodResponse", WrapperNamespace="http://webservices.foodapi.miwfit.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class getFoodResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.foodapi.miwfit.ws.miw.uniovi.es/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSClient.FoodWS.food[] @return;
        
        public getFoodResponse()
        {
        }
        
        public getFoodResponse(WSClient.FoodWS.food[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface FoodProviderChannel : WSClient.FoodWS.FoodProvider, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class FoodProviderClient : System.ServiceModel.ClientBase<WSClient.FoodWS.FoodProvider>, WSClient.FoodWS.FoodProvider
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FoodProviderClient() : 
                base(FoodProviderClient.GetDefaultBinding(), FoodProviderClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.FoodProviderPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FoodProviderClient(EndpointConfiguration endpointConfiguration) : 
                base(FoodProviderClient.GetBindingForEndpoint(endpointConfiguration), FoodProviderClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FoodProviderClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FoodProviderClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FoodProviderClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FoodProviderClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FoodProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.FoodWS.getFoodResponse> WSClient.FoodWS.FoodProvider.getFoodAsync(WSClient.FoodWS.getFoodRequest request)
        {
            return base.Channel.getFoodAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.FoodWS.getFoodResponse> getFoodAsync(double arg0)
        {
            WSClient.FoodWS.getFoodRequest inValue = new WSClient.FoodWS.getFoodRequest();
            inValue.arg0 = arg0;
            return ((WSClient.FoodWS.FoodProvider)(this)).getFoodAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FoodProviderPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FoodProviderPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/ws.miwfit.foodapi/soapws/food");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FoodProviderClient.GetBindingForEndpoint(EndpointConfiguration.FoodProviderPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FoodProviderClient.GetEndpointAddress(EndpointConfiguration.FoodProviderPort);
        }
        
        public enum EndpointConfiguration
        {
            
            FoodProviderPort,
        }
    }
}
