//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.CalculadoraIMCWS
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/")]
    public partial class InvalidDataException
    {
        
        private string faultCodeField;
        
        private string faultStringField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultCode
        {
            get
            {
                return this.faultCodeField;
            }
            set
            {
                this.faultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultString
        {
            get
            {
                return this.faultStringField;
            }
            set
            {
                this.faultStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/")]
    public partial class resultadoIMC
    {
        
        private string actividadField;
        
        private double alturaField;
        
        private double caloriasField;
        
        private double deficitField;
        
        private double imcField;
        
        private double pesoField;
        
        private double pesoIdealField;
        
        private string sexoField;
        
        private double superavitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string actividad
        {
            get
            {
                return this.actividadField;
            }
            set
            {
                this.actividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double altura
        {
            get
            {
                return this.alturaField;
            }
            set
            {
                this.alturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double calorias
        {
            get
            {
                return this.caloriasField;
            }
            set
            {
                this.caloriasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double deficit
        {
            get
            {
                return this.deficitField;
            }
            set
            {
                this.deficitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double imc
        {
            get
            {
                return this.imcField;
            }
            set
            {
                this.imcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double peso
        {
            get
            {
                return this.pesoField;
            }
            set
            {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double pesoIdeal
        {
            get
            {
                return this.pesoIdealField;
            }
            set
            {
                this.pesoIdealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string sexo
        {
            get
            {
                return this.sexoField;
            }
            set
            {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double superavit
        {
            get
            {
                return this.superavitField;
            }
            set
            {
                this.superavitField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/", ConfigurationName="WSClient.CalculadoraIMCWS.CalculatorIMC")]
    public interface CalculatorIMC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/CalculatorIMC/calcularI" +
            "MCRequest", ReplyAction="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/CalculatorIMC/calcularI" +
            "MCResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSClient.CalculadoraIMCWS.InvalidDataException), Action="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/CalculatorIMC/calcularI" +
            "MC/Fault/InvalidDataException", Name="InvalidDataException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSClient.CalculadoraIMCWS.calcularIMCResponse> calcularIMCAsync(WSClient.CalculadoraIMCWS.calcularIMCRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calcularIMC", WrapperNamespace="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class calcularIMCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        public calcularIMCRequest()
        {
        }
        
        public calcularIMCRequest(double arg0, double arg1, string arg2, string arg3)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calcularIMCResponse", WrapperNamespace="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class calcularIMCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.calculadoraimc.miwfit.ws.miw.uniovi.es/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSClient.CalculadoraIMCWS.resultadoIMC @return;
        
        public calcularIMCResponse()
        {
        }
        
        public calcularIMCResponse(WSClient.CalculadoraIMCWS.resultadoIMC @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CalculatorIMCChannel : WSClient.CalculadoraIMCWS.CalculatorIMC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CalculatorIMCClient : System.ServiceModel.ClientBase<WSClient.CalculadoraIMCWS.CalculatorIMC>, WSClient.CalculadoraIMCWS.CalculatorIMC
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CalculatorIMCClient() : 
                base(CalculatorIMCClient.GetDefaultBinding(), CalculatorIMCClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CalculatorIMCPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculatorIMCClient(EndpointConfiguration endpointConfiguration) : 
                base(CalculatorIMCClient.GetBindingForEndpoint(endpointConfiguration), CalculatorIMCClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculatorIMCClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CalculatorIMCClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculatorIMCClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CalculatorIMCClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculatorIMCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.CalculadoraIMCWS.calcularIMCResponse> WSClient.CalculadoraIMCWS.CalculatorIMC.calcularIMCAsync(WSClient.CalculadoraIMCWS.calcularIMCRequest request)
        {
            return base.Channel.calcularIMCAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.CalculadoraIMCWS.calcularIMCResponse> calcularIMCAsync(double arg0, double arg1, string arg2, string arg3)
        {
            WSClient.CalculadoraIMCWS.calcularIMCRequest inValue = new WSClient.CalculadoraIMCWS.calcularIMCRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((WSClient.CalculadoraIMCWS.CalculatorIMC)(this)).calcularIMCAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CalculatorIMCPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CalculatorIMCPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/ws.miwfit.calculadoraIMC/soapws/calculatorIMC");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CalculatorIMCClient.GetBindingForEndpoint(EndpointConfiguration.CalculatorIMCPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CalculatorIMCClient.GetEndpointAddress(EndpointConfiguration.CalculatorIMCPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CalculatorIMCPort,
        }
    }
}
